# Generated by Django 3.2.8 on 2021-10-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('progreso', models.IntegerField()),
                ('idestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipais.estado')),
                ('idpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipais.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='idtipopersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipais.tipopersona'),
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idmediopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipais.mediopago')),
                ('idpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipais.persona')),
                ('idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mipais.proyecto')),
            ],
        ),
    ]
